-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


ALTER TABLE IF EXISTS dsid_dwh.f_devis DROP CONSTRAINT IF EXISTS fk_fait_client;

ALTER TABLE IF EXISTS dsid_dwh.f_devis DROP CONSTRAINT IF EXISTS fk_fait_commercial;

ALTER TABLE IF EXISTS dsid_dwh.f_devis DROP CONSTRAINT IF EXISTS fk_fait_produit;

ALTER TABLE IF EXISTS dsid_dwh.f_devis DROP CONSTRAINT IF EXISTS fk_fait_statut;



DROP TABLE IF EXISTS dsid_dwh.dim_client;

CREATE TABLE IF NOT EXISTS dsid_dwh.dim_client
(
    id_client integer NOT NULL,
    id_client_src integer NOT NULL,
    nom_client character varying(100) COLLATE pg_catalog."default",
    ville_client character varying(100) COLLATE pg_catalog."default",
    etat_client character varying(100) COLLATE pg_catalog."default",
    scd_start timestamp without time zone,
    scd_end timestamp without time zone,
    scd_active boolean,
    scd_version integer,
    _date_creation timestamp without time zone,
    CONSTRAINT dim_client_pkey PRIMARY KEY (id_client)
);

DROP TABLE IF EXISTS dsid_dwh.dim_commercial;

CREATE TABLE IF NOT EXISTS dsid_dwh.dim_commercial
(
    id_commercial integer NOT NULL,
    id_commercial_src integer NOT NULL,
    nom_commercial character varying(100) COLLATE pg_catalog."default",
    profil_commercial character varying(100) COLLATE pg_catalog."default",
    pourcentage_atteint integer,
    _date_creation timestamp without time zone,
    CONSTRAINT dim_commercial_pkey PRIMARY KEY (id_commercial)
);

DROP TABLE IF EXISTS dsid_dwh.dim_produit;

CREATE TABLE IF NOT EXISTS dsid_dwh.dim_produit
(
    id_produit integer NOT NULL,
    id_produit_src integer NOT NULL,
    nom_produit character varying(100) COLLATE pg_catalog."default",
    ancien_nom_produit character varying(100) COLLATE pg_catalog."default",
    type_prestation character varying(100) COLLATE pg_catalog."default",
    categorie_produit character varying(100) COLLATE pg_catalog."default",
    _date_creation timestamp without time zone,
    CONSTRAINT dim_produit_pkey PRIMARY KEY (id_produit)
);

DROP TABLE IF EXISTS dsid_dwh.dim_statut_devis;

CREATE TABLE IF NOT EXISTS dsid_dwh.dim_statut_devis
(
    id_statut integer NOT NULL,
    code_statut character varying(10) COLLATE pg_catalog."default",
    libelle_statut character varying(100) COLLATE pg_catalog."default",
    _date_creation timestamp without time zone,
    CONSTRAINT dim_statut_devis_pkey PRIMARY KEY (id_statut)
);

DROP TABLE IF EXISTS dsid_dwh.f_devis;

CREATE TABLE IF NOT EXISTS dsid_dwh.f_devis
(
    id_devis integer NOT NULL,
    id_client integer,
    id_commercial integer,
    id_produit integer,
    id_statut integer,
    date_creation date,
    date_validation date,
    montant_ht numeric,
    montant_ttc numeric,
    _date_creation timestamp without time zone,
    CONSTRAINT pk_fait_devis PRIMARY KEY (id_devis)
);

DROP TABLE IF EXISTS dsid_raw.info_commercial;

CREATE TABLE IF NOT EXISTS dsid_raw.info_commercial
(
    id_commercial integer,
    profil_commercial character varying(100) COLLATE pg_catalog."default",
    objectifs_total integer,
    objectifs_atteints integer,
    pourcentage_atteint integer
);

DROP TABLE IF EXISTS dsid_raw.suivi_devis;

CREATE TABLE IF NOT EXISTS dsid_raw.suivi_devis
(
    id_societe integer,
    nom_societe character varying(100) COLLATE pg_catalog."default",
    id_devis integer,
    nom_devis character varying(100) COLLATE pg_catalog."default",
    id_client integer,
    nom_client character varying(100) COLLATE pg_catalog."default",
    rue_adresse_client character varying(100) COLLATE pg_catalog."default",
    rue2_adresse_client character varying(100) COLLATE pg_catalog."default",
    ville_client character varying(100) COLLATE pg_catalog."default",
    code_postal_client character varying(100) COLLATE pg_catalog."default",
    id_etat_client integer,
    etat_client character varying(100) COLLATE pg_catalog."default",
    id_pays_client integer,
    pays_client character varying(100) COLLATE pg_catalog."default",
    id_commercial integer,
    nom_commercial character varying(100) COLLATE pg_catalog."default",
    id_type_prestation integer,
    nom_type_prestation character varying(100) COLLATE pg_catalog."default",
    id_produit integer,
    code_produit character varying(100) COLLATE pg_catalog."default",
    nom_produit character varying(100) COLLATE pg_catalog."default",
    description_ligne_devis text COLLATE pg_catalog."default",
    id_categorie_produit integer,
    nom_categorie_produit character varying(100) COLLATE pg_catalog."default",
    code_status_devis character varying(10) COLLATE pg_catalog."default",
    libelle_status_devis character varying(100) COLLATE pg_catalog."default",
    date_creation date,
    date_validation date,
    montant_ht numeric,
    montant_ttc numeric
);

DROP TABLE IF EXISTS dsid_wrk.ods_devis;

CREATE TABLE IF NOT EXISTS dsid_wrk.ods_devis
(
    id_ods_devis integer NOT NULL,
    id_client integer,
    id_commercial integer,
    id_produit integer,
    nom_client character varying(100) COLLATE pg_catalog."default",
    ville_client character varying(100) COLLATE pg_catalog."default",
    etat_client character varying(100) COLLATE pg_catalog."default",
    nom_commercial character varying(100) COLLATE pg_catalog."default",
    profil_commercial character varying(100) COLLATE pg_catalog."default",
    pourcentage_atteint integer,
    type_prestation character varying(100) COLLATE pg_catalog."default",
    categorie_produit character varying(100) COLLATE pg_catalog."default",
    nom_produit character varying(100) COLLATE pg_catalog."default",
    code_statut character varying(10) COLLATE pg_catalog."default",
    libelle_statut character varying(100) COLLATE pg_catalog."default",
    date_creation date,
    date_validation date,
    montant_ht numeric,
    montant_ttc numeric,
    _date_traitement date,
    CONSTRAINT ods_devis_pkey PRIMARY KEY (id_ods_devis)
);

DROP TABLE IF EXISTS dsid_wrk.staging_devis;

CREATE TABLE IF NOT EXISTS dsid_wrk.staging_devis
(
    id_staging_devis integer NOT NULL,
    id_societe integer,
    nom_societe character varying(100) COLLATE pg_catalog."default",
    id_devis integer,
    nom_devis character varying(100) COLLATE pg_catalog."default",
    id_client integer,
    nom_client character varying(100) COLLATE pg_catalog."default",
    rue_adresse_client character varying(100) COLLATE pg_catalog."default",
    rue2_adresse_client character varying(100) COLLATE pg_catalog."default",
    ville_client character varying(100) COLLATE pg_catalog."default",
    code_postal_client character varying(100) COLLATE pg_catalog."default",
    id_etat_client integer,
    etat_client character varying(100) COLLATE pg_catalog."default",
    id_pays_client integer,
    pays_client character varying(100) COLLATE pg_catalog."default",
    id_commercial integer,
    nom_commercial character varying(100) COLLATE pg_catalog."default",
    profil_commercial character varying(100) COLLATE pg_catalog."default",
    objectifs_total integer,
    objectifs_atteints integer,
    pourcentage_atteint integer,
    id_type_prestation integer,
    nom_type_prestation character varying(100) COLLATE pg_catalog."default",
    id_produit integer,
    code_produit character varying(100) COLLATE pg_catalog."default",
    nom_produit character varying(100) COLLATE pg_catalog."default",
    description_ligne_devis text COLLATE pg_catalog."default",
    id_categorie_produit integer,
    nom_categorie_produit character varying(100) COLLATE pg_catalog."default",
    code_status_devis character varying(10) COLLATE pg_catalog."default",
    libelle_status_devis character varying(100) COLLATE pg_catalog."default",
    date_creation date,
    date_validation date,
    montant_ht numeric,
    montant_ttc numeric,
    _date_traitement timestamp without time zone,
    CONSTRAINT staging_devis_pkey PRIMARY KEY (id_staging_devis)
);

ALTER TABLE IF EXISTS dsid_dwh.f_devis
    ADD CONSTRAINT fk_fait_client FOREIGN KEY (id_client)
    REFERENCES dsid_dwh.dim_client (id_client) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS dsid_dwh.f_devis
    ADD CONSTRAINT fk_fait_commercial FOREIGN KEY (id_commercial)
    REFERENCES dsid_dwh.dim_commercial (id_commercial) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS dsid_dwh.f_devis
    ADD CONSTRAINT fk_fait_produit FOREIGN KEY (id_produit)
    REFERENCES dsid_dwh.dim_produit (id_produit) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS dsid_dwh.f_devis
    ADD CONSTRAINT fk_fait_statut FOREIGN KEY (id_statut)
    REFERENCES dsid_dwh.dim_statut_devis (id_statut) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;

===================================================================================
===================================================================================

-- Cette partie du script a été ajoutée manuellement, elle n'est pas générée par l'outil ERD.


-- SEQUENCES - DIMENSIONS ET FAITS
DROP SEQUENCE IF EXISTS dsid_dwh.seq_id_client;
CREATE SEQUENCE dsid_dwh.seq_id_client;

DROP SEQUENCE IF EXISTS dsid_dwh.seq_id_commercial;
CREATE SEQUENCE dsid_dwh.seq_id_commercial;

DROP SEQUENCE IF EXISTS dsid_dwh.seq_id_produit;
CREATE SEQUENCE dsid_dwh.seq_id_produit;

DROP SEQUENCE IF EXISTS dsid_dwh.seq_id_statut;
CREATE SEQUENCE dsid_dwh.seq_id_statut;

DROP SEQUENCE IF EXISTS dsid_dwh.seq_id_date;
CREATE SEQUENCE dsid_dwh.seq_id_date;

DROP SEQUENCE IF EXISTS dsid_dwh.seq_id_devis;
CREATE SEQUENCE dsid_dwh.seq_id_devis;

-- SEQUENCES - STAGING ET ODS
DROP SEQUENCE IF EXISTS dsid_wrk.seq_id_staging_devis;
CREATE SEQUENCE dsid_wrk.seq_id_staging_devis;

DROP SEQUENCE IF EXISTS dsid_wrk.seq_id_ods_devis;
CREATE SEQUENCE dsid_wrk.seq_id_ods_devis;